"""
Clinical AI Agent

AI-powered clinical intelligence for reviewing patient encounters
and generating actionable insights. This demonstrates how AI can
assist clinicians and researchers with data analysis.
"""

from datetime import datetime
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from enum import Enum


class InsightType(str, Enum):
    """Types of clinical insights."""
    ALERT = "alert"
    RECOMMENDATION = "recommendation"
    OBSERVATION = "observation"
    QUALITY_METRIC = "quality_metric"
    RESEARCH_OPPORTUNITY = "research_opportunity"


class Severity(str, Enum):
    """Severity levels for alerts."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class ClinicalInsight:
    """A clinical insight generated by the AI agent."""
    insight_type: InsightType
    severity: Severity
    title: str
    description: str
    evidence: List[str]
    recommendations: List[str]
    relevant_concepts: List[int]


class ClinicalAIAgent:
    """
    AI agent that reviews patient data and generates clinical insights.

    Capabilities:
    1. Patient encounter review
    2. Lab result trend analysis
    3. Drug interaction screening
    4. Quality metric calculation
    5. Research opportunity identification
    """

    # Clinical rules for generating insights
    LAB_CRITICAL_VALUES = {
        "hemoglobin": {"low": 7.0, "high": 20.0, "unit": "g/dL"},
        "potassium": {"low": 2.5, "high": 6.5, "unit": "mEq/L"},
        "sodium": {"low": 120, "high": 160, "unit": "mEq/L"},
        "glucose": {"low": 50, "high": 500, "unit": "mg/dL"},
        "creatinine": {"high": 10.0, "unit": "mg/dL"},
        "platelets": {"low": 20, "unit": "10*9/L"},
    }

    # Drug interaction rules (simplified for demo)
    DRUG_INTERACTIONS = {
        ("warfarin", "aspirin"): "Increased bleeding risk with concurrent anticoagulant/antiplatelet therapy",
        ("metformin", "creatinine_high"): "Metformin contraindicated in severe renal impairment",
        ("tacrolimus", "potassium_high"): "Tacrolimus can exacerbate hyperkalemia",
    }

    # Quality metrics
    QUALITY_METRICS = {
        "diabetes_hba1c_control": {
            "description": "HbA1c < 7% for diabetic patients",
            "target": 7.0,
        },
        "hypertension_bp_control": {
            "description": "Blood pressure < 140/90 for hypertensive patients",
            "systolic_target": 140,
            "diastolic_target": 90,
        },
        "ckd_egfr_monitoring": {
            "description": "eGFR monitoring every 3 months for CKD patients",
            "interval_days": 90,
        },
    }

    def __init__(self):
        self._insights: List[ClinicalInsight] = []
        self._analysis_log: List[Dict] = []

    def analyze_patient_data(
        self,
        patient_token: str,
        person_data: Dict,
        visits: List[Dict],
        conditions: List[Dict],
        measurements: List[Dict],
        drugs: List[Dict],
    ) -> Dict[str, Any]:
        """
        Perform comprehensive analysis of a patient's data.
        """
        insights = []

        # Analyze lab values
        lab_insights = self._analyze_lab_values(patient_token, measurements)
        insights.extend(lab_insights)

        # Analyze drug safety
        drug_insights = self._analyze_drug_safety(patient_token, drugs, measurements, conditions)
        insights.extend(drug_insights)

        # Analyze care quality
        quality_insights = self._analyze_quality_metrics(
            patient_token, conditions, measurements
        )
        insights.extend(quality_insights)

        # Analyze visit patterns
        visit_insights = self._analyze_visit_patterns(patient_token, visits)
        insights.extend(visit_insights)

        # Generate summary
        summary = self._generate_patient_summary(
            person_data, visits, conditions, measurements, drugs
        )

        self._analysis_log.append({
            "patient_token": patient_token,
            "timestamp": datetime.now().isoformat(),
            "insights_generated": len(insights),
        })

        return {
            "patient_token": patient_token,
            "summary": summary,
            "insights": [self._insight_to_dict(i) for i in insights],
            "risk_score": self._calculate_risk_score(insights),
            "analysis_timestamp": datetime.now().isoformat(),
        }

    def _analyze_lab_values(
        self,
        patient_token: str,
        measurements: List[Dict],
    ) -> List[ClinicalInsight]:
        """Analyze lab values for critical findings and trends."""
        insights = []

        # Group measurements by type
        lab_groups: Dict[str, List[Dict]] = {}
        for m in measurements:
            source_value = m.get("measurement_source_value", "unknown")
            if source_value not in lab_groups:
                lab_groups[source_value] = []
            lab_groups[source_value].append(m)

        # Check for critical values
        for lab_name, critical_range in self.LAB_CRITICAL_VALUES.items():
            # Find matching labs by source value pattern
            matching_labs = []
            for source, labs in lab_groups.items():
                if lab_name.lower() in source.lower() or any(
                    lab_name in str(lab.get("measurement_source_value", "")).lower()
                    for lab in labs
                ):
                    matching_labs.extend(labs)

            for lab in matching_labs:
                value = lab.get("value_as_number")
                if value is None:
                    continue

                if "low" in critical_range and value < critical_range["low"]:
                    insights.append(ClinicalInsight(
                        insight_type=InsightType.ALERT,
                        severity=Severity.HIGH,
                        title=f"Critical Low {lab_name.title()}",
                        description=f"{lab_name.title()} value of {value} {critical_range.get('unit', '')} is critically low (threshold: {critical_range['low']})",
                        evidence=[f"Lab result: {value} {critical_range.get('unit', '')}"],
                        recommendations=[
                            "Immediate clinical review recommended",
                            "Consider repeat testing to confirm",
                            "Evaluate for underlying cause",
                        ],
                        relevant_concepts=[lab.get("measurement_concept_id", 0)],
                    ))

                if "high" in critical_range and value > critical_range["high"]:
                    insights.append(ClinicalInsight(
                        insight_type=InsightType.ALERT,
                        severity=Severity.HIGH,
                        title=f"Critical High {lab_name.title()}",
                        description=f"{lab_name.title()} value of {value} {critical_range.get('unit', '')} is critically high (threshold: {critical_range['high']})",
                        evidence=[f"Lab result: {value} {critical_range.get('unit', '')}"],
                        recommendations=[
                            "Immediate clinical review recommended",
                            "Consider repeat testing to confirm",
                            "Initiate appropriate treatment protocol",
                        ],
                        relevant_concepts=[lab.get("measurement_concept_id", 0)],
                    ))

        # Check for trends (simplified)
        for source, labs in lab_groups.items():
            if len(labs) >= 2:
                sorted_labs = sorted(labs, key=lambda x: x.get("measurement_datetime", ""))
                values = [l.get("value_as_number") for l in sorted_labs if l.get("value_as_number")]

                if len(values) >= 2:
                    if all(values[i] < values[i+1] for i in range(len(values)-1)):
                        insights.append(ClinicalInsight(
                            insight_type=InsightType.OBSERVATION,
                            severity=Severity.MEDIUM,
                            title=f"Rising Trend: {source}",
                            description=f"Consistent upward trend observed in {source} values over {len(values)} measurements",
                            evidence=[f"Values: {values}"],
                            recommendations=["Monitor trend", "Consider clinical correlation"],
                            relevant_concepts=[],
                        ))
                    elif all(values[i] > values[i+1] for i in range(len(values)-1)):
                        insights.append(ClinicalInsight(
                            insight_type=InsightType.OBSERVATION,
                            severity=Severity.MEDIUM,
                            title=f"Declining Trend: {source}",
                            description=f"Consistent downward trend observed in {source} values over {len(values)} measurements",
                            evidence=[f"Values: {values}"],
                            recommendations=["Monitor trend", "Consider clinical correlation"],
                            relevant_concepts=[],
                        ))

        return insights

    def _analyze_drug_safety(
        self,
        patient_token: str,
        drugs: List[Dict],
        measurements: List[Dict],
        conditions: List[Dict],
    ) -> List[ClinicalInsight]:
        """Analyze drug safety and potential interactions."""
        insights = []

        drug_names = set()
        for drug in drugs:
            source_value = drug.get("drug_source_value", "").lower()
            # Map common RxNorm codes to drug names
            rxnorm_to_name = {
                "11289": "warfarin",
                "1191": "aspirin",
                "860975": "metformin",
                "42316": "tacrolimus",
            }
            drug_name = rxnorm_to_name.get(source_value, source_value)
            drug_names.add(drug_name)

        # Check for drug-drug interactions
        for (drug1, drug2), warning in self.DRUG_INTERACTIONS.items():
            if drug1 in drug_names and drug2 in drug_names:
                insights.append(ClinicalInsight(
                    insight_type=InsightType.ALERT,
                    severity=Severity.MEDIUM,
                    title="Potential Drug Interaction",
                    description=warning,
                    evidence=[f"Concurrent medications: {drug1}, {drug2}"],
                    recommendations=[
                        "Review medication necessity",
                        "Consider alternative therapy",
                        "Monitor for adverse effects",
                    ],
                    relevant_concepts=[],
                ))

        # Check drug-lab interactions
        for drug in drug_names:
            if drug == "metformin":
                # Check creatinine
                creatinine_labs = [
                    m for m in measurements
                    if "creatinine" in str(m.get("measurement_source_value", "")).lower()
                ]
                for lab in creatinine_labs:
                    if lab.get("value_as_number", 0) > 4.0:
                        insights.append(ClinicalInsight(
                            insight_type=InsightType.ALERT,
                            severity=Severity.HIGH,
                            title="Metformin Contraindication",
                            description="Metformin may be contraindicated due to elevated creatinine suggesting renal impairment",
                            evidence=[f"Creatinine: {lab.get('value_as_number')} mg/dL", "Metformin prescribed"],
                            recommendations=[
                                "Review metformin necessity",
                                "Calculate eGFR",
                                "Consider dose adjustment or alternative",
                            ],
                            relevant_concepts=[],
                        ))
                        break

        return insights

    def _analyze_quality_metrics(
        self,
        patient_token: str,
        conditions: List[Dict],
        measurements: List[Dict],
    ) -> List[ClinicalInsight]:
        """Analyze quality of care metrics."""
        insights = []

        # Check diabetes control
        has_diabetes = any(
            "diabetes" in str(c.get("condition_source_value", "")).lower() or
            c.get("condition_concept_id") == 44054006
            for c in conditions
        )

        if has_diabetes:
            hba1c_labs = [
                m for m in measurements
                if "hba1c" in str(m.get("measurement_source_value", "")).lower() or
                "4548-4" in str(m.get("measurement_source_value", ""))
            ]
            if hba1c_labs:
                latest = max(hba1c_labs, key=lambda x: x.get("measurement_datetime", ""))
                value = latest.get("value_as_number", 0)
                if value > 7.0:
                    insights.append(ClinicalInsight(
                        insight_type=InsightType.QUALITY_METRIC,
                        severity=Severity.MEDIUM,
                        title="Diabetes Control Gap",
                        description=f"HbA1c of {value}% exceeds target of <7% for diabetic patients",
                        evidence=[f"Latest HbA1c: {value}%", "Diagnosis: Diabetes mellitus"],
                        recommendations=[
                            "Review diabetes management plan",
                            "Consider medication intensification",
                            "Reinforce lifestyle modifications",
                            "Schedule follow-up for reassessment",
                        ],
                        relevant_concepts=[44054006],
                    ))
                else:
                    insights.append(ClinicalInsight(
                        insight_type=InsightType.QUALITY_METRIC,
                        severity=Severity.INFO,
                        title="Diabetes Well Controlled",
                        description=f"HbA1c of {value}% is at goal (<7%)",
                        evidence=[f"Latest HbA1c: {value}%"],
                        recommendations=["Continue current management"],
                        relevant_concepts=[44054006],
                    ))

        return insights

    def _analyze_visit_patterns(
        self,
        patient_token: str,
        visits: List[Dict],
    ) -> List[ClinicalInsight]:
        """Analyze visit patterns for care coordination insights."""
        insights = []

        if len(visits) == 0:
            return insights

        # Count visit types
        inpatient_count = sum(1 for v in visits if v.get("visit_concept_id") == 9201)
        emergency_count = sum(1 for v in visits if v.get("visit_concept_id") == 9203)

        if emergency_count >= 2:
            insights.append(ClinicalInsight(
                insight_type=InsightType.OBSERVATION,
                severity=Severity.MEDIUM,
                title="Frequent Emergency Visits",
                description=f"Patient has {emergency_count} emergency department visits",
                evidence=[f"ED visits: {emergency_count}", f"Total visits: {len(visits)}"],
                recommendations=[
                    "Review for care coordination opportunities",
                    "Consider chronic disease management enrollment",
                    "Evaluate for social determinants of health",
                ],
                relevant_concepts=[9203],
            ))

        if inpatient_count >= 2:
            insights.append(ClinicalInsight(
                insight_type=InsightType.OBSERVATION,
                severity=Severity.MEDIUM,
                title="Frequent Hospitalizations",
                description=f"Patient has {inpatient_count} inpatient admissions",
                evidence=[f"Inpatient admissions: {inpatient_count}"],
                recommendations=[
                    "Review for readmission prevention opportunities",
                    "Consider transitional care management",
                    "Evaluate medication reconciliation",
                ],
                relevant_concepts=[9201],
            ))

        return insights

    def _generate_patient_summary(
        self,
        person_data: Dict,
        visits: List[Dict],
        conditions: List[Dict],
        measurements: List[Dict],
        drugs: List[Dict],
    ) -> Dict[str, Any]:
        """Generate a summary of the patient's clinical picture."""
        current_year = datetime.now().year
        age = current_year - person_data.get("year_of_birth", current_year)

        gender_map = {8507: "Male", 8532: "Female", 8551: "Unknown"}
        gender = gender_map.get(person_data.get("gender_concept_id", 8551), "Unknown")

        # Get unique conditions
        unique_conditions = list(set(
            c.get("condition_source_value", "Unknown")
            for c in conditions
        ))

        # Get current medications
        current_meds = list(set(
            d.get("drug_source_value", "Unknown")
            for d in drugs
        ))

        # Get latest labs
        latest_labs = {}
        for m in measurements:
            source = m.get("measurement_source_value", "")
            if source not in latest_labs:
                latest_labs[source] = m
            elif m.get("measurement_datetime", "") > latest_labs[source].get("measurement_datetime", ""):
                latest_labs[source] = m

        return {
            "demographics": {
                "age": age,
                "gender": gender,
            },
            "clinical_summary": {
                "total_visits": len(visits),
                "active_conditions": unique_conditions[:10],  # Top 10
                "current_medications": current_meds[:10],
                "recent_lab_count": len(latest_labs),
            },
            "care_timeline": {
                "earliest_visit": min((v.get("visit_start_date", "") for v in visits), default="N/A"),
                "latest_visit": max((v.get("visit_start_date", "") for v in visits), default="N/A"),
            },
        }

    def _calculate_risk_score(
        self,
        insights: List[ClinicalInsight],
    ) -> Dict[str, Any]:
        """Calculate an overall risk score based on insights."""
        high_count = sum(1 for i in insights if i.severity == Severity.HIGH)
        medium_count = sum(1 for i in insights if i.severity == Severity.MEDIUM)
        low_count = sum(1 for i in insights if i.severity == Severity.LOW)

        # Simple scoring: high=10, medium=5, low=1
        score = high_count * 10 + medium_count * 5 + low_count * 1

        if score >= 20:
            level = "High"
            color = "red"
        elif score >= 10:
            level = "Medium"
            color = "orange"
        elif score > 0:
            level = "Low"
            color = "yellow"
        else:
            level = "Minimal"
            color = "green"

        return {
            "score": score,
            "level": level,
            "color": color,
            "breakdown": {
                "high_severity_findings": high_count,
                "medium_severity_findings": medium_count,
                "low_severity_findings": low_count,
            },
        }

    def _insight_to_dict(self, insight: ClinicalInsight) -> Dict:
        """Convert insight to dictionary."""
        return {
            "type": insight.insight_type.value,
            "severity": insight.severity.value,
            "title": insight.title,
            "description": insight.description,
            "evidence": insight.evidence,
            "recommendations": insight.recommendations,
            "relevant_concepts": insight.relevant_concepts,
        }

    def analyze_cohort(
        self,
        cohort_members: List[int],
        omop_data: Dict[str, List[Dict]],
    ) -> Dict[str, Any]:
        """
        Analyze an entire cohort and generate population-level insights.
        """
        all_insights = []

        for person_id in cohort_members:
            # Get person data
            persons = omop_data.get("person", [])
            person = next((p for p in persons if p["person_id"] == person_id), None)
            if not person:
                continue

            # Get related data
            visits = [v for v in omop_data.get("visit_occurrence", []) if v["person_id"] == person_id]
            conditions = [c for c in omop_data.get("condition_occurrence", []) if c["person_id"] == person_id]
            measurements = [m for m in omop_data.get("measurement", []) if m["person_id"] == person_id]
            drugs = [d for d in omop_data.get("drug_exposure", []) if d["person_id"] == person_id]

            # Analyze individual
            result = self.analyze_patient_data(
                patient_token=person.get("person_source_value", str(person_id)),
                person_data=person,
                visits=visits,
                conditions=conditions,
                measurements=measurements,
                drugs=drugs,
            )
            all_insights.extend(result.get("insights", []))

        # Aggregate insights
        insight_counts: Dict[str, int] = {}
        for insight in all_insights:
            title = insight.get("title", "Unknown")
            insight_counts[title] = insight_counts.get(title, 0) + 1

        top_insights = sorted(insight_counts.items(), key=lambda x: x[1], reverse=True)[:10]

        # Calculate cohort risk distribution
        high_risk = sum(1 for _ in cohort_members if True)  # Simplified

        return {
            "cohort_size": len(cohort_members),
            "total_insights_generated": len(all_insights),
            "top_findings": [
                {"finding": title, "count": count, "prevalence": f"{count/len(cohort_members)*100:.1f}%"}
                for title, count in top_insights
            ],
            "research_opportunities": self._identify_research_opportunities(
                cohort_members, omop_data, all_insights
            ),
        }

    def _identify_research_opportunities(
        self,
        cohort_members: List[int],
        omop_data: Dict[str, List[Dict]],
        insights: List[Dict],
    ) -> List[Dict]:
        """Identify potential research opportunities from the data."""
        opportunities = []

        # Check for interesting patterns
        if len(cohort_members) >= 10:
            opportunities.append({
                "title": "Cohort Study Opportunity",
                "description": f"Cohort of {len(cohort_members)} patients available for retrospective analysis",
                "suggested_analyses": [
                    "Outcomes analysis",
                    "Treatment pattern analysis",
                    "Risk factor identification",
                ],
            })

        # Check for quality improvement opportunities
        quality_findings = [i for i in insights if i.get("type") == "quality_metric"]
        if quality_findings:
            opportunities.append({
                "title": "Quality Improvement Study",
                "description": f"Identified {len(quality_findings)} quality metric gaps",
                "suggested_analyses": [
                    "Care gap closure intervention",
                    "Best practice implementation",
                    "Outcome measurement",
                ],
            })

        return opportunities

    def get_analysis_statistics(self) -> Dict:
        """Get statistics about AI agent analyses performed."""
        return {
            "total_analyses": len(self._analysis_log),
            "recent_analyses": self._analysis_log[-5:],
        }
